name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dos testes
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clonar servidor UI
        run: git clone https://github.com/rm-oliveira/hub-de-leitura-integrado.git

      - name: Instalar dependências do servidor
        run: |
          cd hub-de-leitura-integrado
          npm install

      - name: Subir servidor
        run: |
          cd hub-de-leitura-integrado
          npm start &

      - name: Instalar wait-on
        run: npm install wait-on --no-save

      - name: Aguardar servidor iniciar
        run: npx wait-on http://localhost:3000

      - name: Instalar dependências dos testes
        run: npm install

      - name: Rodar Cypress
        run: npm test